on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
      - name: Download dependencies from apt
        run: |
          sudo apt-get install -y qemu qemu-user-static
      - name: Download hub-tool
        run: |
          curl -OL https://github.com/docker/hub-tool/releases/download/v0.4.6/hub-tool-linux-amd64.tar.gz
      - name: Uncompress hub-tool
        run: |
          ls
          tar -xvzf hub-tool-linux-amd64.tar.gz
          rm hub-tool-linux-amd64.tar.gz
      # - name: Remove old tags from Docker Hub
      #   run: |
      #     echo "To be completed after first push."
      # - name: Create amd64 image and tag it
      #   run: |
      #     docker build -t dhub-test:latest__amd64 --build-arg ARCH=amd64/ .
      #     docker tag dhub-test:latest__amd64 tjdahl/dhub-test:latest__amd64
      # - name: Create arm64 image and tag it
      #   run: |
      #     docker buildx build --platform lanux/arm64 -t dhub-test:latest__arm64 .
      #     docker tag dhub-test:latest__arm64 tjdahl/dhub-test:latest__arm64
      # - name: Generate manifest for images
      #   run: |
      #     docker manifest create \
      #     --amend tjdahl/dhub-test:latest__amd64
      #     --amend tjdahl/dhub-test:latest__arm64
      - name: Log into Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Fool the login command (https://github.com/docker/hub-tool/pull/198)
          # ./hub-tool login
          # Token commands thank to https://stackoverflow.com/a/59334315/5155484
          HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"$DOCKER_USERNAME\", \"password\": \"$DOCKER_PASSWORD\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
          USERNAME="$(printf '%s:' "$DOCKER_USERNAME" | base64 -w0)"
          USER_PASS="$(printf '%s:%s' "$DOCKER_USERNAME" "$DOCKER_PASSWORD" | base64 -w0)"
          mkdir -p ~/.docker/
          printf '{"auths": {"hub-tool": {"auth": "%s"}, "hub-tool-refresh-token": {"auth": "%s"}, "hub-tool-token": { "auth": "%s", "identitytoken": "%s"}}}' \
            "$USER_PASS" "$USERNAME" \
            "$USERNAME" "$HUB_TOKEN" \
            > ~/.docker/config.json
      - name: Test output
        run: |
          ./hub-tool tags
